# Generated by Django 6.0.5 on 2026-05-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_managers"),
        ("core", "0002_remove_providerprofile_languages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="languages",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="core.language"
            ),
        ),
    ]
