# Generated by Django 6.0.5 on 2026-05-23 12:19

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="totp_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_method",
            field=models.CharField(
                blank=True,
                choices=[("sms", "SMS OTP"), ("totp", "Authenticator app (TOTP)")],
                default="",
                max_length=8,
            ),
        ),
    ]
