# Generated by Django 6.0.5 on 2026-05-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_totp_confirmed_user_totp_secret_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="two_factor_method",
        ),
        migrations.AddField(
            model_name="user",
            name="sms_2fa_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
