"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dotenv
from datetime import timedelta

dotenv.load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGOSECRET")
FIELD_ENCRYPTION_KEY = os.environ.get(
    "ENCRYPTION_KEY"
)  # encryption key for sensitive data

AUTH_USER_MODEL = "accounts.User"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "bitstorm-saas-repo.onrender.com"]


# Application definition

INSTALLED_APPS = [
    "core",
    "accounts",  # this has to be here because it is a mini app inside of Django and we need to define here
    "rest_framework",  # this is the Django DRF that we will use as the API layer
    "corsheaders",  # this is required so the frontend and django backend can communicate
    "rest_framework_simplejwt.token_blacklist",  # for refresh token expiration
    "drf_spectacular",  # for swagger integration
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # middleware here is required so Django can wire the apps together
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://bitstorm-saas-repo-1.onrender.com",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",  # this is for cookie storage and recognition by django backend
    "https://bitstorm-saas-repo-1.onrender.com",
]

CORS_ALLOW_CREDENTIALS = True
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Two-factor (TOTP + stub SMS)
TOTP_ISSUER = "BitHealth"
SMS_OTP_STUB_EXPOSE = True  # Return otp_code in API instead of sending SMS
PRE_AUTH_TIMEOUT_SECONDS = 300
SMS_OTP_TIMEOUT_SECONDS = 600


# we are going to use a separate frontend so we don't need to use templates here
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("PGDATABASE"),
        "USER": os.environ.get("PGUSER"),
        "PASSWORD": os.environ.get("PGPASSWORD"),
        "HOST": os.environ.get("PGHOST"),
        "PORT": 5432,
        "OPTIONS": {
            "sslmode": "require",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


# SWAGGER eye candy

SPECTACULAR_SETTINGS = {
    "TITLE": "Bitstorm API",
    "DESCRIPTION": "SaaS backend API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "TAGS": [
        {
            "name": "auth",
            "description": "Registration, login (email/phone/CNP), JWT refresh, logout",
        },
        {
            "name": "2FA-auth",
            "description": "SMS OTP (stub), TOTP authenticator, password reset, 2FA setup",
        },
        {
            "name": "core",
            "description": "Core domain resources (catalog, profiles, reviews)",
        },
        {
            "name": "me",
            "description": "Authenticated user profile and location onboarding",
        },
        {
            "name": "provider",
            "description": "Provider offerings, availability, bookings, invoices",
        },
        {
            "name": "customer",
            "description": "Customer availability, bookings, invoices, payments",
        },
        {
            "name": "marketplace",
            "description": "Public provider discovery and open slot search",
        },
    ],
    # Separate request-body editors per content type in Swagger UI
    "COMPONENT_SPLIT_REQUEST": True,
    #  THIS is what enables JWT auth in Swagger UI
    "SECURITY": [{"BearerAuth": []}],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    # Makes "Authorize" stick after refresh
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
}
