-- Refresh the BitHealth catalog so it only contains medical content.
-- Generated from backend/db/core/*.csv via scripts/generate_medical_sql.py
-- Run inside DBeaver against the same Postgres DB used by Django.

BEGIN;
-- core_service (medical catalog)
UPDATE core_service SET name='Consultație medicină generală', slug='consultatie-medicina-generala-1', description='Consultație medicală pentru evaluarea stării generale de sănătate, diagnostic și plan de tratament.', min_price=150.00, max_price=250.00, is_active=TRUE WHERE id=1;
UPDATE core_service SET name='Consultație pediatrică', slug='consultatie-pediatrica-2', description='Consultație pediatrică pentru sugari, copii și adolescenți, cu examinare clinică completă.', min_price=180.00, max_price=280.00, is_active=TRUE WHERE id=2;
UPDATE core_service SET name='Vaccinare', slug='vaccinare-3', description='Administrare vaccinuri conform schemei naționale și recomandărilor medicale (gripă, hepatită, HPV etc.).', min_price=80.00, max_price=200.00, is_active=TRUE WHERE id=3;
UPDATE core_service SET name='Recoltări analize', slug='recoltari-analize-4', description='Recoltare probe biologice (sânge, urină) la cabinet sau la domiciliu pentru analize de laborator.', min_price=60.00, max_price=150.00, is_active=TRUE WHERE id=4;
UPDATE core_service SET name='Asistență medicală la domiciliu', slug='asistenta-medicala-la-domiciliu-5', description='Servicii de asistență medicală la domiciliu pentru pacienți cu mobilitate redusă, vârstnici sau în convalescență.', min_price=120.00, max_price=300.00, is_active=TRUE WHERE id=5;
UPDATE core_service SET name='Stomatologie generală', slug='stomatologie-generala-6', description='Consultație stomatologică, obturații, tratament carii, urgențe dentare.', min_price=200.00, max_price=500.00, is_active=TRUE WHERE id=6;
UPDATE core_service SET name='Igienizare dentară (detartraj)', slug='igienizare-dentara-detartraj-7', description='Detartraj cu ultrasunete, periaj profesional și airflow pentru o igienă orală completă.', min_price=180.00, max_price=280.00, is_active=TRUE WHERE id=7;
UPDATE core_service SET name='Consultație cardiologie', slug='consultatie-cardiologie-8', description='Consultație cardiologică cu electrocardiogramă (EKG) și recomandări de tratament.', min_price=250.00, max_price=400.00, is_active=TRUE WHERE id=8;
UPDATE core_service SET name='Consultație dermatologie', slug='consultatie-dermatologie-9', description='Examinare dermatoscopică a alunițelor și diagnosticarea afecțiunilor pielii.', min_price=220.00, max_price=350.00, is_active=TRUE WHERE id=9;
UPDATE core_service SET name='Consultație ginecologie', slug='consultatie-ginecologie-10', description='Consult ginecologic complet cu test PAP și ecografie transvaginală la cerere.', min_price=230.00, max_price=380.00, is_active=TRUE WHERE id=10;
UPDATE core_service SET name='Fizioterapie', slug='fizioterapie-11', description='Ședințe de fizioterapie cu electrostimulare, ultrasunete și magnetoterapie.', min_price=100.00, max_price=200.00, is_active=TRUE WHERE id=11;
UPDATE core_service SET name='Kinetoterapie', slug='kinetoterapie-12', description='Recuperare prin mișcare pentru afecțiuni musculo-scheletale, post-traumatice sau neurologice.', min_price=120.00, max_price=220.00, is_active=TRUE WHERE id=12;
UPDATE core_service SET name='Recuperare medicală post-operatorie', slug='recuperare-medicala-post-operatorie-13', description='Program personalizat de recuperare după intervenții chirurgicale ortopedice sau cardiovasculare.', min_price=150.00, max_price=350.00, is_active=TRUE WHERE id=13;
UPDATE core_service SET name='Nutriție clinică', slug='nutritie-clinica-14', description='Consult nutrițional cu plan dietetic personalizat pentru diabet, obezitate sau alte afecțiuni.', min_price=180.00, max_price=300.00, is_active=TRUE WHERE id=14;
UPDATE core_service SET name='Consultație ortopedie', slug='consultatie-ortopedie-15', description='Examinare ortopedică, tratament conservator sau recomandare chirurgicală pentru afecțiuni osoase și articulare.', min_price=240.00, max_price=400.00, is_active=TRUE WHERE id=15;
UPDATE core_service SET name='Consultație neurologie', slug='consultatie-neurologie-16', description='Consult neurologic pentru migrene, vertij, epilepsie și alte afecțiuni ale sistemului nervos.', min_price=260.00, max_price=420.00, is_active=TRUE WHERE id=16;
UPDATE core_service SET name='Consultație ORL', slug='consultatie-orl-17', description='Examinare otorinolaringologică pentru afecțiunile urechii, nasului și gâtului.', min_price=200.00, max_price=330.00, is_active=TRUE WHERE id=17;
UPDATE core_service SET name='Consultație oftalmologie', slug='consultatie-oftalmologie-18', description='Examen oftalmologic complet, prescripție ochelari și screening pentru glaucom.', min_price=210.00, max_price=340.00, is_active=TRUE WHERE id=18;
UPDATE core_service SET name='Logopedie', slug='logopedie-19', description='Terapie logopedică pentru tulburări de vorbire, dislalie, balbism la copii și adulți.', min_price=150.00, max_price=250.00, is_active=TRUE WHERE id=19;
UPDATE core_service SET name='Psihoterapie / Consiliere psihologică', slug='psihoterapie-consiliere-psihologica-20', description='Ședințe de psihoterapie individuală pentru anxietate, depresie și gestionarea stresului.', min_price=200.00, max_price=350.00, is_active=TRUE WHERE id=20;
UPDATE core_service SET name='Consultație medicină generală', slug='consultatie-medicina-generala-21', description='Consultație medicală pentru evaluarea stării generale de sănătate, diagnostic și plan de tratament.', min_price=150.00, max_price=250.00, is_active=TRUE WHERE id=21;
UPDATE core_service SET name='Consultație pediatrică', slug='consultatie-pediatrica-22', description='Consultație pediatrică pentru sugari, copii și adolescenți, cu examinare clinică completă.', min_price=180.00, max_price=280.00, is_active=TRUE WHERE id=22;
UPDATE core_service SET name='Vaccinare', slug='vaccinare-23', description='Administrare vaccinuri conform schemei naționale și recomandărilor medicale (gripă, hepatită, HPV etc.).', min_price=80.00, max_price=200.00, is_active=TRUE WHERE id=23;
UPDATE core_service SET name='Recoltări analize', slug='recoltari-analize-24', description='Recoltare probe biologice (sânge, urină) la cabinet sau la domiciliu pentru analize de laborator.', min_price=60.00, max_price=150.00, is_active=TRUE WHERE id=24;
UPDATE core_service SET name='Asistență medicală la domiciliu', slug='asistenta-medicala-la-domiciliu-25', description='Servicii de asistență medicală la domiciliu pentru pacienți cu mobilitate redusă, vârstnici sau în convalescență.', min_price=120.00, max_price=300.00, is_active=TRUE WHERE id=25;
UPDATE core_service SET name='Stomatologie generală', slug='stomatologie-generala-26', description='Consultație stomatologică, obturații, tratament carii, urgențe dentare.', min_price=200.00, max_price=500.00, is_active=TRUE WHERE id=26;
UPDATE core_service SET name='Igienizare dentară (detartraj)', slug='igienizare-dentara-detartraj-27', description='Detartraj cu ultrasunete, periaj profesional și airflow pentru o igienă orală completă.', min_price=180.00, max_price=280.00, is_active=TRUE WHERE id=27;
UPDATE core_service SET name='Consultație cardiologie', slug='consultatie-cardiologie-28', description='Consultație cardiologică cu electrocardiogramă (EKG) și recomandări de tratament.', min_price=250.00, max_price=400.00, is_active=TRUE WHERE id=28;
UPDATE core_service SET name='Consultație dermatologie', slug='consultatie-dermatologie-29', description='Examinare dermatoscopică a alunițelor și diagnosticarea afecțiunilor pielii.', min_price=220.00, max_price=350.00, is_active=TRUE WHERE id=29;
UPDATE core_service SET name='Consultație ginecologie', slug='consultatie-ginecologie-30', description='Consult ginecologic complet cu test PAP și ecografie transvaginală la cerere.', min_price=230.00, max_price=380.00, is_active=TRUE WHERE id=30;
UPDATE core_service SET name='Fizioterapie', slug='fizioterapie-31', description='Ședințe de fizioterapie cu electrostimulare, ultrasunete și magnetoterapie.', min_price=100.00, max_price=200.00, is_active=TRUE WHERE id=31;
UPDATE core_service SET name='Kinetoterapie', slug='kinetoterapie-32', description='Recuperare prin mișcare pentru afecțiuni musculo-scheletale, post-traumatice sau neurologice.', min_price=120.00, max_price=220.00, is_active=TRUE WHERE id=32;
UPDATE core_service SET name='Recuperare medicală post-operatorie', slug='recuperare-medicala-post-operatorie-33', description='Program personalizat de recuperare după intervenții chirurgicale ortopedice sau cardiovasculare.', min_price=150.00, max_price=350.00, is_active=TRUE WHERE id=33;
UPDATE core_service SET name='Nutriție clinică', slug='nutritie-clinica-34', description='Consult nutrițional cu plan dietetic personalizat pentru diabet, obezitate sau alte afecțiuni.', min_price=180.00, max_price=300.00, is_active=TRUE WHERE id=34;
UPDATE core_service SET name='Consultație ortopedie', slug='consultatie-ortopedie-35', description='Examinare ortopedică, tratament conservator sau recomandare chirurgicală pentru afecțiuni osoase și articulare.', min_price=240.00, max_price=400.00, is_active=TRUE WHERE id=35;
UPDATE core_service SET name='Consultație neurologie', slug='consultatie-neurologie-36', description='Consult neurologic pentru migrene, vertij, epilepsie și alte afecțiuni ale sistemului nervos.', min_price=260.00, max_price=420.00, is_active=TRUE WHERE id=36;
UPDATE core_service SET name='Consultație ORL', slug='consultatie-orl-37', description='Examinare otorinolaringologică pentru afecțiunile urechii, nasului și gâtului.', min_price=200.00, max_price=330.00, is_active=TRUE WHERE id=37;
UPDATE core_service SET name='Consultație oftalmologie', slug='consultatie-oftalmologie-38', description='Examen oftalmologic complet, prescripție ochelari și screening pentru glaucom.', min_price=210.00, max_price=340.00, is_active=TRUE WHERE id=38;
UPDATE core_service SET name='Logopedie', slug='logopedie-39', description='Terapie logopedică pentru tulburări de vorbire, dislalie, balbism la copii și adulți.', min_price=150.00, max_price=250.00, is_active=TRUE WHERE id=39;
UPDATE core_service SET name='Psihoterapie / Consiliere psihologică', slug='psihoterapie-consiliere-psihologica-40', description='Ședințe de psihoterapie individuală pentru anxietate, depresie și gestionarea stresului.', min_price=200.00, max_price=350.00, is_active=TRUE WHERE id=40;
UPDATE core_service SET name='Consultație medicină generală', slug='consultatie-medicina-generala-41', description='Consultație medicală pentru evaluarea stării generale de sănătate, diagnostic și plan de tratament.', min_price=150.00, max_price=250.00, is_active=TRUE WHERE id=41;
UPDATE core_service SET name='Consultație pediatrică', slug='consultatie-pediatrica-42', description='Consultație pediatrică pentru sugari, copii și adolescenți, cu examinare clinică completă.', min_price=180.00, max_price=280.00, is_active=TRUE WHERE id=42;
UPDATE core_service SET name='Vaccinare', slug='vaccinare-43', description='Administrare vaccinuri conform schemei naționale și recomandărilor medicale (gripă, hepatită, HPV etc.).', min_price=80.00, max_price=200.00, is_active=TRUE WHERE id=43;
UPDATE core_service SET name='Recoltări analize', slug='recoltari-analize-44', description='Recoltare probe biologice (sânge, urină) la cabinet sau la domiciliu pentru analize de laborator.', min_price=60.00, max_price=150.00, is_active=TRUE WHERE id=44;
UPDATE core_service SET name='Asistență medicală la domiciliu', slug='asistenta-medicala-la-domiciliu-45', description='Servicii de asistență medicală la domiciliu pentru pacienți cu mobilitate redusă, vârstnici sau în convalescență.', min_price=120.00, max_price=300.00, is_active=TRUE WHERE id=45;
UPDATE core_service SET name='Stomatologie generală', slug='stomatologie-generala-46', description='Consultație stomatologică, obturații, tratament carii, urgențe dentare.', min_price=200.00, max_price=500.00, is_active=TRUE WHERE id=46;
UPDATE core_service SET name='Igienizare dentară (detartraj)', slug='igienizare-dentara-detartraj-47', description='Detartraj cu ultrasunete, periaj profesional și airflow pentru o igienă orală completă.', min_price=180.00, max_price=280.00, is_active=TRUE WHERE id=47;
UPDATE core_service SET name='Consultație cardiologie', slug='consultatie-cardiologie-48', description='Consultație cardiologică cu electrocardiogramă (EKG) și recomandări de tratament.', min_price=250.00, max_price=400.00, is_active=TRUE WHERE id=48;
UPDATE core_service SET name='Consultație dermatologie', slug='consultatie-dermatologie-49', description='Examinare dermatoscopică a alunițelor și diagnosticarea afecțiunilor pielii.', min_price=220.00, max_price=350.00, is_active=TRUE WHERE id=49;
UPDATE core_service SET name='Consultație ginecologie', slug='consultatie-ginecologie-50', description='Consult ginecologic complet cu test PAP și ecografie transvaginală la cerere.', min_price=230.00, max_price=380.00, is_active=TRUE WHERE id=50;

-- core_providerprofile (medical professions)
UPDATE core_providerprofile SET display_name='Medic stomatolog — Laura Rusu', bio='Medic stomatolog cu peste 10 ani de experiență în stomatologie generală și igienizare dentară.', is_active=TRUE WHERE id=1;
UPDATE core_providerprofile SET display_name='Kinetoterapeut — Tudor Dumitru', bio='Kinetoterapeut specializat în recuperare medicală și fizioterapie pentru pacienți de toate vârstele.', is_active=TRUE WHERE id=2;
UPDATE core_providerprofile SET display_name='Medic radiolog — Teodora Dumitru', bio='Medic radiolog specializat în imagistică medicală și diagnostic ecografic.', is_active=TRUE WHERE id=3;
UPDATE core_providerprofile SET display_name='Medic ginecolog — Florin Nistor', bio='Medic ginecolog cu experiență în consultații prenatale și îngrijirea sănătății femeii.', is_active=TRUE WHERE id=4;
UPDATE core_providerprofile SET display_name='Medic cardiolog — Tudor Luca', bio='Medic cardiolog dedicat prevenției și tratamentului afecțiunilor cardiovasculare.', is_active=TRUE WHERE id=5;
UPDATE core_providerprofile SET display_name='Medic radiolog — Ana Dumitru', bio='Medic radiolog cu experiență în ecografie abdominală, mamografie și RMN.', is_active=TRUE WHERE id=6;
UPDATE core_providerprofile SET display_name='Medic cardiolog — Mihai Neagu', bio='Medic cardiolog cu peste 15 ani de practică, specializat în EKG și holter.', is_active=TRUE WHERE id=7;
UPDATE core_providerprofile SET display_name='Kinetoterapeut — Daniel Popa', bio='Kinetoterapeut autorizat, cu experiență în recuperare post-operatorie și neuromotorie.', is_active=TRUE WHERE id=8;
UPDATE core_providerprofile SET display_name='Psiholog clinician — Ionuț Florescu', bio='Psiholog clinician care oferă consiliere psihologică și suport pentru anxietate și depresie.', is_active=TRUE WHERE id=9;
UPDATE core_providerprofile SET display_name='Medic cardiolog — Bianca Cojocaru', bio='Medic cardiolog cu competență în cardiologie pediatrică și ecocardiografie.', is_active=TRUE WHERE id=10;
UPDATE core_providerprofile SET display_name='Medic dermatolog — Cristian Cojocaru', bio='Medic dermatolog specializat în diagnosticarea și tratarea afecțiunilor pielii.', is_active=TRUE WHERE id=11;
UPDATE core_providerprofile SET display_name='Fizioterapeut — Nicolae Neagu', bio='Fizioterapeut autorizat, cu experiență în electroterapie, magnetoterapie și recuperare medicală.', is_active=TRUE WHERE id=12;
UPDATE core_providerprofile SET display_name='Medic pediatru — Gabriel Luca', bio='Medic pediatru pasionat de îngrijirea sănătății sugarilor, copiilor și adolescenților.', is_active=TRUE WHERE id=14;
UPDATE core_providerprofile SET display_name='Fizioterapeut — Cristina Bălan', bio='Fizioterapeut cu experiență în recuperare neuromotorie și tratament conservator.', is_active=TRUE WHERE id=15;
UPDATE core_providerprofile SET display_name='Medic dermatolog — Gabriela Stan', bio='Medic dermatolog specializat în dermatoscopie și screening pentru leziuni cutanate.', is_active=TRUE WHERE id=16;
UPDATE core_providerprofile SET display_name='Fizioterapeut — Sergiu Stan', bio='Fizioterapeut, specialist în recuperare post-traumatică și kinetoterapie.', is_active=TRUE WHERE id=19;
UPDATE core_providerprofile SET display_name='Kinetoterapeut — Paula Matei', bio='Kinetoterapeut cu experiență în recuperare ortopedică și terapie manuală.', is_active=TRUE WHERE id=21;
UPDATE core_providerprofile SET display_name='Medic cardiolog — Carmen Constantin', bio='Medic cardiolog cu experiență în prevenția și tratamentul afecțiunilor cardiovasculare.', is_active=TRUE WHERE id=22;
UPDATE core_providerprofile SET display_name='Medic stomatolog — Sergiu Stan', bio='Medic stomatolog cu experiență în stomatologie generală, detartraj și obturații.', is_active=TRUE WHERE id=23;
UPDATE core_providerprofile SET display_name='Medic ORL — Constantin Dumitru', bio='Medic ORL specializat în afecțiuni ale urechii, nasului și gâtului.', is_active=TRUE WHERE id=24;
UPDATE core_providerprofile SET display_name='Medic generalist — Daniel Dima', bio='Medic de medicină generală oferind consultații preventive și tratament personalizat.', is_active=TRUE WHERE id=25;
UPDATE core_providerprofile SET display_name='Medic ORL — Carmen Matei', bio='Medic ORL cu experiență în audiometrie, endoscopie nazală și tratamentul sinuzitelor.', is_active=TRUE WHERE id=26;
UPDATE core_providerprofile SET display_name='Kinetoterapeut — Raluca Ionescu', bio='Kinetoterapeut specializat în recuperare medicală pentru pacienți de toate vârstele.', is_active=TRUE WHERE id=28;
UPDATE core_providerprofile SET display_name='Medic ginecolog — Cristian Bălan', bio='Medic ginecolog cu experiență în controale ginecologice de rutină și ecografie pelvină.', is_active=TRUE WHERE id=29;
UPDATE core_providerprofile SET display_name='Medic ORL — Adrian Popescu', bio='Medic ORL dedicat tratamentului afecțiunilor cronice și acute ORL.', is_active=TRUE WHERE id=30;
UPDATE core_providerprofile SET display_name='Medic ginecolog — Ana Dumitru', bio='Medic ginecolog specializat în consultații prenatale și screening (test PAP).', is_active=TRUE WHERE id=32;
UPDATE core_providerprofile SET display_name='Medic ginecolog — Cristina Matei', bio='Medic ginecolog cu experiență în îngrijirea sănătății femeii și planificare familială.', is_active=TRUE WHERE id=33;
UPDATE core_providerprofile SET display_name='Medic ortoped — Paula Vlad', bio='Medic ortoped specializat în afecțiuni ale aparatului locomotor și recuperare post-traumatică.', is_active=TRUE WHERE id=34;
UPDATE core_providerprofile SET display_name='Psiholog clinician — Gabriel Stoica', bio='Psiholog clinician oferind psihoterapie cognitiv-comportamentală pentru adulți și copii.', is_active=TRUE WHERE id=36;
UPDATE core_providerprofile SET display_name='Medic pediatru — Raluca Luca', bio='Medic pediatru cu experiență în vaccinări și consultații pediatrice de rutină.', is_active=TRUE WHERE id=38;
UPDATE core_providerprofile SET display_name='Kinetoterapeut — Bianca Vlad', bio='Kinetoterapeut cu peste 8 ani de experiență în kinetoterapie pediatrică și pentru adulți.', is_active=TRUE WHERE id=39;
UPDATE core_providerprofile SET display_name='Medic radiolog — Andreea Stoica', bio='Medic radiolog specializat în diagnostic imagistic și tomografie computerizată.', is_active=TRUE WHERE id=40;
UPDATE core_providerprofile SET display_name='Medic ORL — Gabriela Popescu', bio='Medic ORL cu experiență în otorinolaringologie pediatrică și pentru adulți.', is_active=TRUE WHERE id=42;
UPDATE core_providerprofile SET display_name='Fizioterapeut — Teodora Cojocaru', bio='Fizioterapeut, specialist în electroterapie, ultrasunete și recuperare medicală.', is_active=TRUE WHERE id=43;
UPDATE core_providerprofile SET display_name='Psiholog clinician — Mihaela Cojocaru', bio='Psiholog clinician cu experiență în terapie pentru depresie, anxietate și gestionarea stresului.', is_active=TRUE WHERE id=44;
UPDATE core_providerprofile SET display_name='Psiholog clinician — Alexandru Gheorghe', bio='Psiholog clinician oferind consiliere psihologică pentru adulți și consiliere de cuplu.', is_active=TRUE WHERE id=47;
UPDATE core_providerprofile SET display_name='Medic cardiolog — Teodora Luca', bio='Medic cardiolog dedicată prevenirii bolilor cardiovasculare și screeningului cardiac.', is_active=TRUE WHERE id=49;
UPDATE core_providerprofile SET display_name='Psiholog clinician — Adrian Popescu', bio='Psiholog clinician oferind suport psihologic pentru pacienți cu afecțiuni cronice.', is_active=TRUE WHERE id=50;

-- core_userprofile (medical interests)
UPDATE core_userprofile SET bio='Pacient interesat de consultații de medicină generală și controale periodice.' WHERE id=1;
UPDATE core_userprofile SET bio='Pacient interesat de consultații pediatrice pentru cei mici.' WHERE id=2;
UPDATE core_userprofile SET bio='Pacient interesat de consultații cardiologice și prevenție cardiovasculară.' WHERE id=3;
UPDATE core_userprofile SET bio='Pacient interesat de fizioterapie și recuperare medicală post-traumatică.' WHERE id=4;
UPDATE core_userprofile SET bio='Pacient interesat de stomatologie generală și igienizare dentară.' WHERE id=5;
UPDATE core_userprofile SET bio='Pacient interesat de servicii de vaccinare conform schemei naționale.' WHERE id=6;
UPDATE core_userprofile SET bio='Pacient interesat de kinetoterapie pentru afecțiuni musculo-scheletale.' WHERE id=7;
UPDATE core_userprofile SET bio='Pacient interesat de consultații dermatologice și controale alunițe.' WHERE id=8;
UPDATE core_userprofile SET bio='Pacient interesat de psihoterapie și consiliere pentru gestionarea stresului.' WHERE id=9;
UPDATE core_userprofile SET bio='Pacient interesat de consultații neurologice pentru migrene cronice.' WHERE id=10;
UPDATE core_userprofile SET bio='Pacient interesat de asistență medicală la domiciliu pentru un membru al familiei vârstnic.' WHERE id=11;
UPDATE core_userprofile SET bio='Pacient interesat de consultații ginecologice de rutină și screening (test PAP).' WHERE id=12;
UPDATE core_userprofile SET bio='Pacient interesat de consultații oftalmologice și prescripție ochelari.' WHERE id=14;
UPDATE core_userprofile SET bio='Pacient interesat de consultații ORL pentru afecțiuni recurente ale gâtului.' WHERE id=15;
UPDATE core_userprofile SET bio='Pacient interesat de logopedie pentru copilul său.' WHERE id=16;
UPDATE core_userprofile SET bio='Pacient interesat de nutriție clinică și plan dietetic personalizat.' WHERE id=17;
UPDATE core_userprofile SET bio='Pacient interesat de recoltare analize la domiciliu.' WHERE id=18;
UPDATE core_userprofile SET bio='Pacient interesat de consultații ortopedice pentru o problemă la genunchi.' WHERE id=19;
UPDATE core_userprofile SET bio='Pacient interesat de fizioterapie și recuperare după o entorsă.' WHERE id=20;
UPDATE core_userprofile SET bio='Pacient interesat de consultații de medicină generală și recomandări pentru analize.' WHERE id=22;
UPDATE core_userprofile SET bio='Pacient interesat de kinetoterapie pediatrică pentru copilul său.' WHERE id=23;
UPDATE core_userprofile SET bio='Pacient interesat de consultații cardiologice și monitorizare tensiune arterială.' WHERE id=25;
UPDATE core_userprofile SET bio='Pacient interesat de psihoterapie pentru anxietate și depresie.' WHERE id=28;
UPDATE core_userprofile SET bio='Pacient interesat de stomatologie generală și controale dentare anuale.' WHERE id=29;
UPDATE core_userprofile SET bio='Pacient interesat de servicii de vaccinare antigripală.' WHERE id=30;
UPDATE core_userprofile SET bio='Pacient interesat de consultații dermatologice pentru acnee.' WHERE id=33;
UPDATE core_userprofile SET bio='Pacient interesat de asistență medicală la domiciliu pentru părinții vârstnici.' WHERE id=37;
UPDATE core_userprofile SET bio='Pacient interesat de recuperare medicală post-operatorie.' WHERE id=39;
UPDATE core_userprofile SET bio='Pacient interesat de consiliere psihologică și suport emoțional.' WHERE id=41;
UPDATE core_userprofile SET bio='Pacient interesat de igienizare dentară periodică (detartraj).' WHERE id=47;

-- core_userreview (medical-themed feedback)
UPDATE core_userreview SET comment='Tratament corect, dar timpul de așteptare a fost lung.' WHERE id=1;
UPDATE core_userreview SET comment='Diagnostic dat în grabă, nu am primit explicații suficiente.' WHERE id=2;
UPDATE core_userreview SET comment='Cabinet curat, dar comunicarea cu personalul a fost dificilă.' WHERE id=3;
UPDATE core_userreview SET comment='Psiholog empatic și foarte bine pregătit. Recomand cu încredere.' WHERE id=4;
UPDATE core_userreview SET comment='Diagnostic precis și plan de tratament clar. Mulțumesc!' WHERE id=5;
UPDATE core_userreview SET comment='Medic stomatolog excelent, intervenția a fost nedureroasă.' WHERE id=6;
UPDATE core_userreview SET comment='Profesionist și punctual, am primit toate explicațiile necesare.' WHERE id=7;
UPDATE core_userreview SET comment='Foarte mulțumit de ședințele de fizioterapie, durerea s-a redus simțitor.' WHERE id=8;
UPDATE core_userreview SET comment='Consultație ORL completă, recomand pentru orice problemă de gât sau urechi.' WHERE id=9;
UPDATE core_userreview SET comment='Medic ORL atent, a tratat problema rapid și eficient.' WHERE id=10;
UPDATE core_userreview SET comment='Consultația radiologică a durat mai mult decât m-am așteptat.' WHERE id=11;
UPDATE core_userreview SET comment='Tratament stomatologic de calitate, recomand cabinetul.' WHERE id=12;
UPDATE core_userreview SET comment='Kinetoterapeutul a întârziat și ședința a fost mai scurtă.' WHERE id=13;
UPDATE core_userreview SET comment='Am așteptat mult, dar tratamentul în sine a fost ok.' WHERE id=14;
UPDATE core_userreview SET comment='Calitatea consultației psihologice a fost sub așteptările mele.' WHERE id=15;
UPDATE core_userreview SET comment='Fizioterapeut amabil, dar program flexibil greu de prins.' WHERE id=16;
UPDATE core_userreview SET comment='Cabinet curat, dar prețul mi s-a părut ridicat pentru un detartraj.' WHERE id=17;
UPDATE core_userreview SET comment='Medic ginecolog foarte profesionist și calm, recomand!' WHERE id=18;
UPDATE core_userreview SET comment='Consultație dermatologică completă, am primit recomandări utile.' WHERE id=19;
UPDATE core_userreview SET comment='Psiholog clinician răbdător, m-a ajutat să gestionez anxietatea.' WHERE id=20;
UPDATE core_userreview SET comment='Medic cardiolog excelent, EKG-ul a fost interpretat detaliat.' WHERE id=21;
UPDATE core_userreview SET comment='Aș fi preferat o discuție mai aprofundată după consultație.' WHERE id=22;
UPDATE core_userreview SET comment='Consultație ginecologică ok, dar timpul alocat a fost scurt.' WHERE id=23;
UPDATE core_userreview SET comment='Medic cardiolog atent, dar a fost necesară reprogramarea.' WHERE id=24;
UPDATE core_userreview SET comment='Tratamentul stomatologic a decurs bine, fără durere.' WHERE id=25;
UPDATE core_userreview SET comment='Medicul a fost grăbit, nu am primit suficiente explicații.' WHERE id=26;
UPDATE core_userreview SET comment='Cardiolog dedicat, mi-a explicat toate rezultatele EKG.' WHERE id=27;
UPDATE core_userreview SET comment='Cabinet stomatologic modern, dar prețurile sunt cam mari.' WHERE id=28;
UPDATE core_userreview SET comment='Așteptarea a fost lungă, deși aveam programare.' WHERE id=29;
UPDATE core_userreview SET comment='Diagnostic radiologic clar și rapid. Recomand.' WHERE id=30;
UPDATE core_userreview SET comment='Tratament stomatologic corect, asistenta foarte amabilă.' WHERE id=31;
UPDATE core_userreview SET comment='Mulțumită de igienizarea dentară, dinții arată mult mai bine.' WHERE id=32;
UPDATE core_userreview SET comment='Tratament stomatologic mediocru, voi încerca alt cabinet.' WHERE id=33;
UPDATE core_userreview SET comment='Programare greu de obținut, deși medicul în sine este ok.' WHERE id=34;
UPDATE core_userreview SET comment='Consultație ginecologică superficială, am rămas cu nelămuriri.' WHERE id=35;
UPDATE core_userreview SET comment='Kinetoterapeutul a fost bun, dar sala era aglomerată.' WHERE id=36;
UPDATE core_userreview SET comment='Medic stomatolog corect, dar asistentul a fost grăbit.' WHERE id=37;
UPDATE core_userreview SET comment='Mulțumită de modul în care a decurs consultația stomatologică.' WHERE id=38;
UPDATE core_userreview SET comment='Medic ORL foarte profesionist, mi-a rezolvat problema rapid.' WHERE id=39;
UPDATE core_userreview SET comment='Kinetoterapeut empatic și răbdător cu pacientul vârstnic.' WHERE id=40;
UPDATE core_userreview SET comment='Recepția stomatologiei a fost dezorganizată.' WHERE id=41;
UPDATE core_userreview SET comment='Recuperarea medicală a fost eficientă, recomand kinetoterapeutul.' WHERE id=42;
UPDATE core_userreview SET comment='Medic stomatolog excelent, profesionist și empatic.' WHERE id=43;
UPDATE core_userreview SET comment='Consultația de medicină generală a fost prea scurtă.' WHERE id=44;
UPDATE core_userreview SET comment='Programul cabinetului ginecologic este restrâns, greu de prins programare.' WHERE id=45;
UPDATE core_userreview SET comment='Psiholog atent, m-a ajutat să mă liniștesc și să găsesc soluții.' WHERE id=46;
UPDATE core_userreview SET comment='Igienizare dentară impecabilă, recomand cu căldură.' WHERE id=47;
UPDATE core_userreview SET comment='Fizioterapie utilă, dar aș fi vrut mai multă personalizare.' WHERE id=48;
UPDATE core_userreview SET comment='Medic ginecolog excelent, foarte răbdător cu paciente.' WHERE id=49;
UPDATE core_userreview SET comment='Servicii stomatologice de top, personal medical empatic.' WHERE id=50;

-- core_providerreview (medical-themed feedback)
UPDATE core_providerreview SET comment='Pacient cooperant, a respectat recomandările medicale.' WHERE id=1;
UPDATE core_providerreview SET comment='Pacient nepunctual, a întârziat aproape o oră la consultație.' WHERE id=2;
UPDATE core_providerreview SET comment='Pacient comunicativ, dar a refuzat parțial planul de tratament.' WHERE id=3;
UPDATE core_providerreview SET comment='Pacient foarte responsabil, urmează tratamentul cu strictețe.' WHERE id=4;
UPDATE core_providerreview SET comment='Pacient agitat în timpul ședinței de psihoterapie.' WHERE id=5;
UPDATE core_providerreview SET comment='Pacient atent la indicații, recuperare în parametri normali.' WHERE id=6;
UPDATE core_providerreview SET comment='Pacient model, comunică simptomele clar și respectă programările.' WHERE id=7;
UPDATE core_providerreview SET comment='Pacient nu a urmat tratamentul prescris între ședințe.' WHERE id=8;
UPDATE core_providerreview SET comment='Pacient anxios, a anulat programarea în mai multe rânduri.' WHERE id=9;
UPDATE core_providerreview SET comment='Pacient cooperant, dar are dificultăți în a urma dieta recomandată.' WHERE id=10;
UPDATE core_providerreview SET comment='Pacient punctual, a adus toate analizele necesare.' WHERE id=11;
UPDATE core_providerreview SET comment='Pacient care necesită explicații suplimentare repetate.' WHERE id=12;
UPDATE core_providerreview SET comment='Pacient extrem de implicat în recuperarea sa medicală.' WHERE id=13;
UPDATE core_providerreview SET comment='Pacient care nu a respectat regulile de igienă post-tratament.' WHERE id=14;
UPDATE core_providerreview SET comment='Pacient care întrerupe frecvent ședința de consiliere.' WHERE id=15;
UPDATE core_providerreview SET comment='Pacient calm, comunică simptomele cu acuratețe.' WHERE id=16;
UPDATE core_providerreview SET comment='Pacient deschis la sugestii, foarte plăcut de tratat.' WHERE id=17;
UPDATE core_providerreview SET comment='Pacient model, respectă cu strictețe planul de tratament dentar.' WHERE id=18;
UPDATE core_providerreview SET comment='Pacient bine informat, întreabă lucrurile potrivite.' WHERE id=19;
UPDATE core_providerreview SET comment='Pacient care confirmă greu programările.' WHERE id=20;
UPDATE core_providerreview SET comment='Pacient care nu a finalizat seria de ședințe de fizioterapie.' WHERE id=21;
UPDATE core_providerreview SET comment='Pacient extraordinar, ușor de tratat și foarte recunoscător.' WHERE id=22;
UPDATE core_providerreview SET comment='Pacient cooperant, evoluție bună după prima ședință.' WHERE id=23;
UPDATE core_providerreview SET comment='Pacient politicos, dar uită medicația prescrisă.' WHERE id=24;
UPDATE core_providerreview SET comment='Pacient empatic și colaborant pe tot parcursul terapiei.' WHERE id=25;
UPDATE core_providerreview SET comment='Pacient care a refuzat efectuarea analizelor recomandate.' WHERE id=26;
UPDATE core_providerreview SET comment='Pacient care a întârziat în mod repetat la programări.' WHERE id=27;
UPDATE core_providerreview SET comment='Pacient atent la igienă, evoluție stomatologică bună.' WHERE id=28;
UPDATE core_providerreview SET comment='Pacient calm, dar are reticențe la administrarea injecțiilor.' WHERE id=29;
UPDATE core_providerreview SET comment='Pacient implicat și responsabil cu recuperarea medicală.' WHERE id=30;
UPDATE core_providerreview SET comment='Pacient calm, prezintă simptomele detaliat.' WHERE id=31;
UPDATE core_providerreview SET comment='Pacient cooperant, deși a întârziat la o programare.' WHERE id=32;
UPDATE core_providerreview SET comment='Pacient care nu a respectat indicațiile post-consultație.' WHERE id=33;
UPDATE core_providerreview SET comment='Pacient model, plăcere să-l consult.' WHERE id=34;
UPDATE core_providerreview SET comment='Pacient anxios, am avut nevoie de mai mult timp pentru consultație.' WHERE id=35;
UPDATE core_providerreview SET comment='Pacient care întrerupe explicațiile medicale.' WHERE id=36;
UPDATE core_providerreview SET comment='Pacient care a venit fără analizele cerute.' WHERE id=37;
UPDATE core_providerreview SET comment='Pacient politicos și foarte răbdător la tratament.' WHERE id=38;
UPDATE core_providerreview SET comment='Pacient extrem de cooperant, recuperare excelentă după ortopedie.' WHERE id=39;
UPDATE core_providerreview SET comment='Pacient implicat în recuperarea kinetoterapeutică.' WHERE id=40;
UPDATE core_providerreview SET comment='Pacient care a întrerupt tratamentul fără consultare.' WHERE id=41;
UPDATE core_providerreview SET comment='Pacient care necesită multe consultații pentru aceeași problemă.' WHERE id=42;
UPDATE core_providerreview SET comment='Pacient calm, înțelege explicațiile cardiologice.' WHERE id=43;
UPDATE core_providerreview SET comment='Pacient care urmează cu succes terapia.' WHERE id=44;
UPDATE core_providerreview SET comment='Pacient instabil cu prezența la programări.' WHERE id=45;
UPDATE core_providerreview SET comment='Pacient amabil, dar are nevoie de monitorizare suplimentară.' WHERE id=46;
UPDATE core_providerreview SET comment='Pacient excelent, recomand cu drag colegilor medici.' WHERE id=47;
UPDATE core_providerreview SET comment='Pacient cooperant, deși are nelămuriri repetate post-consultație.' WHERE id=48;
UPDATE core_providerreview SET comment='Pacient care nu a respectat dieta recomandată.' WHERE id=49;
UPDATE core_providerreview SET comment='Pacient model, totul a decurs perfect la consultația dermatologică.' WHERE id=50;

COMMIT;
