/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderIndexRouteImport } from './routes/provider/index'
import { Route as BookingsIndexRouteImport } from './routes/bookings/index'
import { Route as ProvidersIdRouteImport } from './routes/providers/$id'
import { Route as ProviderServicesRouteImport } from './routes/provider/services'
import { Route as ProviderScheduleRouteImport } from './routes/provider/schedule'
import { Route as ProviderOnboardingRouteImport } from './routes/provider/onboarding'
import { Route as ProviderBookingsRouteImport } from './routes/provider/bookings'
import { Route as BookingsNewRouteImport } from './routes/bookings/new'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/provider/',
  path: '/provider/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderServicesRoute = ProviderServicesRouteImport.update({
  id: '/provider/services',
  path: '/provider/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderScheduleRoute = ProviderScheduleRouteImport.update({
  id: '/provider/schedule',
  path: '/provider/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderOnboardingRoute = ProviderOnboardingRouteImport.update({
  id: '/provider/onboarding',
  path: '/provider/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderBookingsRoute = ProviderBookingsRouteImport.update({
  id: '/provider/bookings',
  path: '/provider/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/sign-up': typeof SignUpRoute
  '/bookings/new': typeof BookingsNewRoute
  '/provider/bookings': typeof ProviderBookingsRoute
  '/provider/onboarding': typeof ProviderOnboardingRoute
  '/provider/schedule': typeof ProviderScheduleRoute
  '/provider/services': typeof ProviderServicesRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/provider/': typeof ProviderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/sign-up': typeof SignUpRoute
  '/bookings/new': typeof BookingsNewRoute
  '/provider/bookings': typeof ProviderBookingsRoute
  '/provider/onboarding': typeof ProviderOnboardingRoute
  '/provider/schedule': typeof ProviderScheduleRoute
  '/provider/services': typeof ProviderServicesRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/bookings': typeof BookingsIndexRoute
  '/provider': typeof ProviderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/sign-up': typeof SignUpRoute
  '/bookings/new': typeof BookingsNewRoute
  '/provider/bookings': typeof ProviderBookingsRoute
  '/provider/onboarding': typeof ProviderOnboardingRoute
  '/provider/schedule': typeof ProviderScheduleRoute
  '/provider/services': typeof ProviderServicesRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/provider/': typeof ProviderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/sign-up'
    | '/bookings/new'
    | '/provider/bookings'
    | '/provider/onboarding'
    | '/provider/schedule'
    | '/provider/services'
    | '/providers/$id'
    | '/bookings/'
    | '/provider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/sign-up'
    | '/bookings/new'
    | '/provider/bookings'
    | '/provider/onboarding'
    | '/provider/schedule'
    | '/provider/services'
    | '/providers/$id'
    | '/bookings'
    | '/provider'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/sign-up'
    | '/bookings/new'
    | '/provider/bookings'
    | '/provider/onboarding'
    | '/provider/schedule'
    | '/provider/services'
    | '/providers/$id'
    | '/bookings/'
    | '/provider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SignUpRoute: typeof SignUpRoute
  BookingsNewRoute: typeof BookingsNewRoute
  ProviderBookingsRoute: typeof ProviderBookingsRoute
  ProviderOnboardingRoute: typeof ProviderOnboardingRoute
  ProviderScheduleRoute: typeof ProviderScheduleRoute
  ProviderServicesRoute: typeof ProviderServicesRoute
  ProvidersIdRoute: typeof ProvidersIdRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  ProviderIndexRoute: typeof ProviderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/': {
      id: '/provider/'
      path: '/provider'
      fullPath: '/provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/services': {
      id: '/provider/services'
      path: '/provider/services'
      fullPath: '/provider/services'
      preLoaderRoute: typeof ProviderServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/schedule': {
      id: '/provider/schedule'
      path: '/provider/schedule'
      fullPath: '/provider/schedule'
      preLoaderRoute: typeof ProviderScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/onboarding': {
      id: '/provider/onboarding'
      path: '/provider/onboarding'
      fullPath: '/provider/onboarding'
      preLoaderRoute: typeof ProviderOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/bookings': {
      id: '/provider/bookings'
      path: '/provider/bookings'
      fullPath: '/provider/bookings'
      preLoaderRoute: typeof ProviderBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SignUpRoute: SignUpRoute,
  BookingsNewRoute: BookingsNewRoute,
  ProviderBookingsRoute: ProviderBookingsRoute,
  ProviderOnboardingRoute: ProviderOnboardingRoute,
  ProviderScheduleRoute: ProviderScheduleRoute,
  ProviderServicesRoute: ProviderServicesRoute,
  ProvidersIdRoute: ProvidersIdRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  ProviderIndexRoute: ProviderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
