# Generated by Django 6.0.5 on 2026-05-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="providerprofile",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="languages",
        ),
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, max_length=128, unique=True),
        ),
    ]
